//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session2
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryChangeProducts
    {
        public long ID { get; set; }
        public Nullable<decimal> OldMinPrice { get; set; }
        public Nullable<decimal> NewMinPrice { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
