//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materials()
        {
            this.ProductsMaterials = new HashSet<ProductsMaterials>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public Nullable<long> MaterialTypeID { get; set; }
        public Nullable<int> QuantityInBox { get; set; }
        public Nullable<long> VolumeValuesID { get; set; }
        public Nullable<int> QuantityInSclad { get; set; }
        public Nullable<int> MinQuantity { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual MaterialTypes MaterialTypes { get; set; }
        public virtual VolumeValues VolumeValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsMaterials> ProductsMaterials { get; set; }
    }
}
