//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<long> Article { get; set; }
        public Nullable<decimal> MinPrice { get; set; }
        public string Image { get; set; }
        public Nullable<long> ProductTypeID { get; set; }
        public int Quantity { get; set; }
        public Nullable<long> FactoryID { get; set; }
    
        public virtual ProductsTypes ProductsTypes { get; set; }
    }
}
